### ISSUE TITLE
refactor: toggle behavior

### ISSUE THREAD

**Issue by vinicius-sacramento** [agicommies/commune-page#67]
## Objective

_Check if makes sense to take off the dropdown and change the feature flow._

**First state**:  The default theme will be based on the user system and set the moon or sun icon depending on the theme.

**Second state**: User interaction must change the theme.

![Image](https://github.com/agicommies/commune-page/assets/50849605/eb7a2cb2-e7de-4315-9a6f-a756d0dcfc18)

**Comment by EdSDR** [comment]
@steinerkelvin

**Comment by steinerkelvin** [comment]
@EdSDR your call
