### ISSUE TITLE
feature: add new animation to hero section

### ISSUE THREAD

**Issue by EdSDR** [agicommies/commune-page#68]
https://github.com/agicommies/commune-page/assets/89485015/79eeb572-22d7-4fc6-a439-49e868011a7d
https://github.com/agicommies/commune-page/assets/89485015/7edc849f-4265-4318-90e5-85b39cfbd7bb

**Comment by steinerkelvin** [comment]
I'll just ask to avoid tracking 1MB files with git.

Also, the PNG might be useful as a placeholder:

![commune_logo_animation_frame](https://github.com/agicommies/commune-page/assets/2822370/80fd79fd-de1e-479b-9be3-18d98b0e576a)

**Comment by EdSDR** [comment]
@steinerkelvin just finished the feature with the lottie, you can check it here: https://github.com/agicommies/commune-page/pull/73, the only thing missing is the png sequence so i can make the lottie without the black background.
